project:
  type: book
  output-dir: _book

book:
  title: "The Cosmic Counselor"
  subtitle: "Ethical Spiritual Guidance in Modern Times"
  author: "Bishal Ghimire"
  
  chapters:
    # Home page with all frontmatter
    - index.qmd

    # Frontmatter
    - frontmatter/prologue.qmd
    - frontmatter/foreword.qmd
    - frontmatter/gratitude.qmd
    - frontmatter/preface.qmd
    
    # Main chapters
    - part: "Part I: Foundation"
      chapters:
        - chapters/chapter-01/index.qmd
        - chapters/chapter-01/practice.qmd
        - chapters/chapter-01/quiz.qmd
    
    # Backmatter
    - backmatter/summary.qmd
    - backmatter/references.qmd

format:
  html:
    theme: 
      - cosmo
      - styles/global.scss
    css: 
      - styles/chapter.scss
      - styles/practice.scss
      - styles/quiz.scss
    toc: true
    toc-depth: 3
    number-sections: true
  
  pdf:
    documentclass: book
    toc: true
    number-sections: true
