project:
  type: book
  output-dir: _book
  resources:
    - scripts/

book:
  title: "The Cosmic Counselor"
  subtitle: "Ethical Spiritual Guidance in Modern Times"
  author: "Bishal Ghimire"
  
  chapters:
    # Home page with all frontmatter
    - index.qmd

    # Frontmatter
    - frontmatter/prologue.qmd
    - frontmatter/foreword.qmd
    - frontmatter/gratitude.qmd
    - frontmatter/preface.qmd
    
    # Main chapters
    - part: "Chapters"
      chapters:
        - chapters/chapter-01.qmd
    
    # Backmatter
    - backmatter/summary.qmd
    - backmatter/references.qmd

format:
  html:
    theme: 
      - cosmo
    css:
      - styles/global.scss 
      - styles/chapter.scss
      - styles/quiz.scss
      - styles/practice.scss

    toc: true
    toc-depth: 3
    number-sections: true
  
  pdf:
    documentclass: book
    toc: true
    number-sections: true
    keep-tex: true
    
  epub:
    toc: true
    number-sections: true

# GitHub Pages configuration
website:
  site-url: "https://astro-fusion.github.io/the-cosmic-counselor"
  repo-url: "https://github.com/astro-fusion/The-Cosmic-Counselor"

publish:
  - provider: gh-pages
    url: "https://astro-fusion.github.io/the-cosmic-counselor"
