name: Render Translations

on:
  push:
    branches: [ main, feature/translations-hi-ne ]
    paths:
      - 'translations/**'
      - 'assets/**'
      - 'styles/**'
      - 'scripts/**'
      - '.github/workflows/render-translations.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'translations/**'
      - 'assets/**'
      - 'styles/**'
      - 'scripts/**'
      - '.github/workflows/render-translations.yml'

jobs:
  render-nepali:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: pre-release
    
    - name: Install TinyTeX
      uses: r-lib/actions/setup-tinytex@v2
    
    - name: Install system fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-noto-devanagari
        fc-cache -fv
    
    - name: Install LaTeX packages
      run: |
        tlmgr install collection-fontsrecommended
        tlmgr install fontspec
        tlmgr install enumitem
    
    - name: Render Nepali PDF
      run: |
        quarto render translations/ne --to pdf
    
    - name: Render Nepali HTML
      run: |
        quarto render translations/ne --to html
    
    - name: Upload Nepali artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nepali-translations
        path: |
          generated/ne/*.pdf
          generated/ne/_book/
          generated/ne/*.html
        retention-days: 30

  render-hindi:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: pre-release
    
    - name: Install TinyTeX
      uses: r-lib/actions/setup-tinytex@v2
    
    - name: Install system fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-noto-devanagari
        fc-cache -fv
    
    - name: Install LaTeX packages
      run: |
        tlmgr install collection-fontsrecommended
        tlmgr install fontspec
        tlmgr install enumitem
    
    - name: Render Hindi PDF
      run: |
        quarto render translations/hi --to pdf
    
    - name: Render Hindi HTML
      run: |
        quarto render translations/hi --to html
    
    - name: Upload Hindi artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hindi-translations
        path: |
          translations/hi/_book/hi/*.pdf
          translations/hi/_book/
          translations/hi/_book/*.html
        retention-days: 30
